### ISSUE TITLE
Error while compiling: OpenNexus.cs(2772,68): error CS0117: BaseEntity.Flags does not contain a definition for Protected

### ISSUE THREAD

**Issue by jkole4** [bmgjet/OpenNexus#1]
Error while compiling: OpenNexus.cs(2772,68): error CS0117: BaseEntity.Flags does not contain a definition for Protected

Happening on the latest aux version 08/02/22 with latest version of oxide v2.0.4004

**Comment by bmgjet** [comment]
Sounds like your replacing the Aux files with main or staging files.
Flag Protected is only in the AUX01 server files which you have to make your own oxide patcher file for since its not the same as staging.

**Comment by bmgjet** [comment]
Just ran the updater on it, AUX01 files havnt changed for last 2 weeks.
Still version 2.0.5369
![image](https://user-images.githubusercontent.com/50484759/152922661-ae25ad2c-b974-4af0-9832-cb0bfdc000fb.png)

**Comment by bmgjet** [comment]
[RustAUX.zip](https://github.com/bmgjet/OpenNexus/files/8020999/RustAUX.zip)
Heres the patcher file Iv edited to get most things working. Some hooks still broken since im not intrested in fixing hooks just needed the ones im using to develop this to work.

**Comment by jkole4** [comment]
Yea I had it pointed to Aux01 also tried fresh installing the server multiple times.

![Untitled](https://user-images.githubusercontent.com/44350845/152927863-3e2b14b4-b0f2-486b-8882-a7a99e0505d9.jpg)
![Untitled2](https://user-images.githubusercontent.com/44350845/152928846-2a7c8629-019a-4119-8ae3-0d4fbb630a7d.jpg)

**Comment by jkole4** [comment]
Also patched Oxide with the patcher file you provided on the version you have installed in the photo as well.

**Comment by bmgjet** [comment]
Fresh install from steamcmd of aux01 branch.
Fresh patch with the file I posted.
Ill just make a clone of this server and upload it.
![image](https://user-images.githubusercontent.com/50484759/152937160-a3d56916-72e6-48c5-84f0-c734665207b3.png)

**Comment by bmgjet** [comment]
https://mega.nz/file/3LhAlSaL#k_wslKBZhQI5408WI4-lXLgnup07PwwyuajA78oF8Cc

**Comment by jkole4** [comment]
thanks for that working now. Dunno what it was doing to break it, I done a fresh install of it from steamcmd of aux01 and a fresh patch on mine and my other admins PC. Now at least we can test it and get ready for when it comes
